version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/" # `.github/workflows`
      - "/.github/actions/*"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
